# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 14:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170507_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_birth',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 10, 7, 0, 94489)),
        ),
    ]
