# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 14:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170507_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_birth',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 10, 33, 35, 824759)),
        ),
    ]
