# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-07 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170507_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_birth',
            field=models.DateField(default=datetime.datetime(2017, 5, 7, 15, 52, 39, 100504)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
